---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: centos-7.3
    driver:
      box: bento/centos-7.3
  - name: centos-6.7
    driver:
      box: bento/centos-6.7
  - name: windows-2012r2
    driver:
      provider: virtualbox
      box:  opentable/win-2012r2-standard-amd64-nocm
      network:
        - ["private_network", {ip: "192.168.33.33"}]

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/inspec

suites:
  - name: zabbix-agent
    run_list:
      - recipe[chef-client::config]
      - recipe[chef-client::windows_service]
      - recipe[chef-client::delete_validation]
      - recipe[zabbix_lwrp::repository]
      - recipe[zabbix_lwrp::agent_win]

  - name: zabbix24-mysql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix24_mysql]
    excludes:
      - windows-2012r2
      - ubuntu-16.04
    verifier:
      attributes:
        db: mysql

  - name: zabbix24-postgresql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix24_postgresql]
    excludes:
      - windows-2012r2
      - ubuntu-16.04
    verifier:
      attributes:
        db: postgresql

  - name: zabbix30-mysql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix30_mysql]
    excludes:
      - windows-2012r2
    verifier:
      attributes:
        db: mysql

  - name: zabbix30-postgresql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix30_postgresql]
    excludes:
      - windows-2012r2
    verifier:
      attributes:
        db: postgresql

  - name: zabbix32-mysql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32_mysql]
    excludes:
      - windows-2012r2
    verifier:
      attributes:
        db: mysql

  - name: zabbix32-mysql-run-state
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32_mysql]
    excludes:
      - windows-2012r2
    verifier:
      attributes:
        db: mysql
    attributes:
      zabbix:
        server:
          credentials:
            databag: wrapper
          database:
            databag: wrapper
            mysql:
              databag: wrapper


  - name: zabbix32-postgresql
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32_postgresql]
    excludes:
      - windows-2012r2
    verifier:
      attributes:
        db: postgresql

  - name: zabbix32-postgresql-run-state
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32_postgresql]
    excludes:
      - windows-2012r2
    verifier:
      attributes:
        db: postgresql
        attributes:
      zabbix:
        server:
          credentials:
            databag: wrapper
          database:
            databag: wrapper
            postgresql:
              databag: wrapper

