require 'spec_helper'

if os[:family] == 'ubuntu'
 repo_file = '/etc/apt/sources.list.d/zabbix-official.list'
 postgresql_dir = '/var/lib/postgresql'
 zabbix_web_package = 'zabbix-frontend-php'
 if os[:release] == '14.04'
   php_pgsql_package = 'php5-pgsql'
   php_zabbix_pool_file = '/etc/php5/fpm/pool.d/zabbix.conf'
 elsif os[:release] == '16.04'
   php_pgsql_package = 'php-pgsql'
   php_zabbix_pool_file = '/etc/php/7.0/fpm/pool.d/zabbix.conf'
 end
end

describe file(repo_file) do
  it { should be_file }
end

describe package('zabbix-agent') do
  it { should be_installed }
end

describe service('zabbix-agent') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/opt/zabbix/etc') do
  it { should be_directory }
end

describe file('/opt/zabbix/scripts') do
  it { should be_directory }
end

describe file('/opt/zabbix/templates') do
  it { should be_directory }
end

describe file('/etc/zabbix/zabbix_agentd.conf') do
  it { should be_file }
  it { should contain 'This file is generated by Chef' }
end

describe port(10_050) do
  it { should be_listening }
end

describe package('zabbixapi') do
  let(:path) { '/opt/chef/embedded/bin:$PATH' }
  it { should be_installed.by('gem') }
end

describe file(postgresql_dir) do
  it { should be_directory }
  it { should be_writable.by_user('postgres') }
  # Check LVM creation on ubuntu only and not Amazon
  if os[:family] == 'ubuntu' and not host_inventory['ec2']['ami-id']
    it { should be_mounted.with(options: { device: '/dev/mapper/shared-zabbix--database' }) }
  end
end

describe command('pg_lsclusters ') do
  its(:stdout) { should match '9.4 main    5432 online postgres /var/lib/postgresql/9.4/main' }
end

describe package('zabbix-server-pgsql') do
  it { should be_installed }
end

describe service('zabbix-server') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/etc/zabbix/zabbix_server.conf') do
  it { should be_file }
  it { should contain 'generated by Chef' }
  it { should contain 'DBName=zabbix' }
  it { should contain 'DBPassword=fced396df30cc3590d8a0deeeaf3eb70' }
  it { should contain 'DBUser=zabbix' }
  it { should contain 'DBHost=127.0.0.1' }
  it { should contain 'DBPort=5432' }
  it { should contain 'ListenIP=0.0.0.0' }
end

describe port(10_051) do
  it { should be_listening }
end

describe package(php_pgsql_package) do
  it { should be_installed }
end

describe package(zabbix_web_package) do
  it { should be_installed }
end

describe file(php_zabbix_pool_file) do
  it { should be_file }
  it { should contain 'listen = 127.0.0.1:9200' }
end

describe port(9200) do
  it { should be_listening }
end

describe file('/etc/zabbix/web/zabbix.conf.php') do
  it { should be_file }
  it { should contain 'generated by Chef' }
  it { should contain '127.0.0.1' }
  it { should contain '5432' }
  it { should contain 'fced396df30cc3590d8a0deeeaf3eb70' }
  it { should contain 'localhost' }
  it { should contain '10051' }
end

describe file('/etc/nginx/sites-available/localhost') do
  it { should be_file }
  it { should contain 'listen   80' }
  it { should contain 'server_name  localhost' }
  it { should contain 'fastcgi_pass    127.0.0.1:9200' }
end

describe port(80) do
  it { should be_listening }
end
