# # encoding: utf-8

# Inspec default test

# The Inspec reference, with examples and extensive documentation, can be
# found at http://inspec.io/docs/reference/resources/

with_lvm = attribute('with_lvm', default: false, description: 'Check lvm partition')

if os[:family] == 'debian'
  repo_file = '/etc/apt/sources.list.d/zabbix-official.list'
  mysql_dir = '/var/lib/mysql_zabbix'
  zabbix_web_package = 'zabbix-frontend-php'
  if os[:release] == '14.04'
    php_mysql_package = 'php5-mysql'
    php_zabbix_pool_file = '/etc/php5/fpm/pool.d/zabbix.conf'
  elsif os[:release] == '16.04'
    php_mysql_package = 'php-mysql'
    php_zabbix_pool_file = '/etc/php/7.0/fpm/pool.d/zabbix.conf'
  end
elsif os[:family] == 'redhat'
  repo_file = '/etc/yum.repos.d/zabbix.repo'
  mysql_dir = '/var/lib/mysql_zabbix'
  zabbix_web_package = 'zabbix-web'
  php_mysql_package = 'php-mysql'
  php_zabbix_pool_file = '/etc/php-fpm.d/zabbix.conf'
end

describe file(repo_file) do
  it { should be_file }
end

describe package('zabbix-agent') do
  it { should be_installed }
end

describe service('zabbix-agent') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/opt/zabbix/etc') do
  it { should be_directory }
end

describe file('/opt/zabbix/scripts') do
  it { should be_directory }
end

describe file('/opt/zabbix/templates') do
  it { should be_directory }
end

describe file('/etc/zabbix/zabbix_agentd.conf') do
  it { should be_file }
  its('content') { should include'This file is generated by Chef' }
end

describe port(10_050) do
  it { should be_listening }
end

describe gem('zabbixapi', '/opt/chef/embedded/bin/gem') do
  it { should be_installed }
end

describe file(mysql_dir) do
  it { should be_directory }
  it { should be_writable.by_user('mysql') }
end

# Check LVM creation only on ubuntu and when with_lvm==true
if (os[:family] == 'debian') && with_lvm
  describe mount(mysql_dir) do
    it { should be_mounted }
    its('device') { should eq '/dev/mapper/shared-zabbix--database' }
  end
end

describe package('zabbix-server-mysql') do
  it { should be_installed }
end

describe service('zabbix-server') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/etc/zabbix/zabbix_server.conf') do
  it { should be_file }
  its('content') { should include'generated by Chef' }
  its('content') { should include'DBName=zabbix' }
  its('content') { should include'DBPassword=fced396df30cc3590d8a0deeeaf3eb70' }
  its('content') { should include'DBUser=zabbix' }
  its('content') { should include'DBHost=127.0.0.1' }
  its('content') { should include'DBPort=3306' }
  its('content') { should include'ListenIP=0.0.0.0' }
end

describe port(10_051) do
  it { should be_listening }
end

describe port(3306) do
  it { should be_listening }
end

describe service('mysql-zabbix') do
  it { should be_enabled }
  it { should be_running }
end

describe package(php_mysql_package) do
  it { should be_installed }
end

describe package(zabbix_web_package) do
  it { should be_installed }
end

describe file(php_zabbix_pool_file) do
  it { should be_file }
  its('content') { should include'listen = 127.0.0.1:9200' }
end

describe port(9200) do
  it { should be_listening }
end

describe file('/etc/zabbix/web/zabbix.conf.php') do
  it { should be_file }
  its('content') { should include'generated by Chef' }
  its('content') { should include'MYSQL' }
  its('content') { should include'127.0.0.1' }
  its('content') { should include'3306' }
  its('content') { should include'fced396df30cc3590d8a0deeeaf3eb70' }
  its('content') { should include'localhost' }
  its('content') { should include'10051' }
end

describe file('/etc/nginx/sites-available/localhost') do
  it { should be_file }
  its('content') { should include'listen   80' }
  its('content') { should include'server_name  localhost' }
  its('content') { should include'fastcgi_pass    127.0.0.1:9200' }
end

describe port(80) do
  it { should be_listening }
end
