# # encoding: utf-8

# Inspec default test

# The Inspec reference, with examples and extensive documentation, can be
# found at http://inspec.io/docs/reference/resources/

with_lvm = attribute('with_lvm', default: false, description: 'Check lvm partition')
db_vendor = attribute('db', default: 'postgresql', description: 'Used database')
db_user = db_vendor == 'mysql' ? 'mysql' : 'postgres'
db_port = db_vendor == 'mysql' ? 3306 : 5432
zabbix_server_package = db_vendor == 'mysql' ? 'zabbix-server-mysql' : 'zabbix-server-pgsql'

case os[:family]
when 'debian'
  repo_file = '/etc/apt/sources.list.d/zabbix-official.list'
  db_dir = db_vendor == 'mysql' ? '/var/lib/mysql_zabbix' : '/var/lib/postgresql'
  zabbix_web_package = 'zabbix-frontend-php'
  case os[:release]
  when '14.04'
    php_db_package = db_vendor == 'mysql' ? 'php5-mysql' : 'php5-pgsql'
    php_zabbix_pool_file = '/etc/php5/fpm/pool.d/zabbix.conf'
  when '16.04'
    php_db_package = db_vendor == 'mysql' ? 'php-mysql' : 'php-pgsql'
    php_zabbix_pool_file = '/etc/php/7.0/fpm/pool.d/zabbix.conf'
  end
when 'redhat'
  repo_file = '/etc/yum.repos.d/zabbix.repo'
  db_dir = db_vendor == 'mysql' ? '/var/lib/mysql_zabbix' : '/var/lib/pgsql'
  zabbix_web_package = 'zabbix-web'
  php_db_package = 'php-pgsql'
  php_zabbix_pool_file = '/etc/php-fpm.d/zabbix.conf'
end

describe file(repo_file) do
  it { should be_file }
end

describe package('zabbix-agent') do
  it { should be_installed }
end

describe service('zabbix-agent') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/opt/zabbix/etc') do
  it { should be_directory }
end

describe file('/opt/zabbix/scripts') do
  it { should be_directory }
end

describe file('/etc/zabbix/zabbix_agentd.conf') do
  it { should be_file }
  its('content') { should include 'This file is generated by Chef' }
end

describe port(10_050) do
  it { should be_listening }
end

describe gem('zabbixapi', '/opt/chef/embedded/bin/gem') do
  it { should be_installed }
end

describe file(db_dir) do
  it { should be_directory }
  it { should be_writable.by_user(db_user) }
end

# Check LVM creation only on ubuntu and when with_lvm==true
if (os[:family] == 'debian') && with_lvm
  describe mount(db_dir) do
    it { should be_mounted }
    its('device') { should eq '/dev/mapper/shared-zabbix--database' }
  end
end

# On CentOS uses old version of postgresql and this command is not exists

if os[:family] == 'debian' && db_vendor == 'postgres'
  describe command('pg_lsclusters') do
    its(:stdout) { should include('main    5432 online postgres') }
  end
end

describe package zabbix_server_package do
  it { should be_installed }
end

describe service('zabbix-server') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/opt/zabbix/templates') do
  it { should be_directory }
end

describe file('/etc/zabbix/zabbix_server.conf') do
  it { should be_file }
  its('content') { should include 'generated by Chef' }
  its('content') { should include 'DBName=zabbix' }
  its('content') { should include 'DBPassword=fced396df30cc3590d8a0deeeaf3eb70' }
  its('content') { should include 'DBUser=zabbix' }
  its('content') { should include 'DBHost=127.0.0.1' }
  its('content') { should include "DBPort=#{db_port}" }
  its('content') { should include 'ListenIP=0.0.0.0' }
  its('content') { should include 'JavaGateway=127.0.0.1' }
end

describe port(10_051) do
  it { should be_listening }
end

describe port(db_port) do
  it { should be_listening }
end

describe package(php_db_package) do
  it { should be_installed }
end

describe package(zabbix_web_package) do
  it { should be_installed }
end

describe file(php_zabbix_pool_file) do
  it { should be_file }
  its('content') { should include 'listen = /var/run/php-fpm-zabbix.sock' }
end

describe file('/var/run/php-fpm-zabbix.sock') do
  it { should be_socket }
end

describe file('/etc/zabbix/web/zabbix.conf.php') do
  it { should be_file }
  its('content') { should include 'generated by Chef' }
  its('content') { should include db_vendor.upcase.to_s }
  its('content') { should include '127.0.0.1' }
  its('content') { should include db_port.to_s }
  its('content') { should include 'fced396df30cc3590d8a0deeeaf3eb70' }
  its('content') { should include 'localhost' }
  its('content') { should include '10051' }
end

describe file('/etc/nginx/sites-available/localhost') do
  it { should be_file }
  its('content') { should include 'listen   80' }
  its('content') { should include 'server_name  localhost' }
  its('content') { should include 'fastcgi_pass    unix:/var/run/php-fpm-zabbix.sock' }
end

describe port(80) do
  it { should be_listening }
end

describe port(10_052) do
  it { should be_listening }
end

describe package('zabbix-java-gateway') do
  it { should be_installed }
end

describe service('zabbix-java-gateway') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/etc/zabbix/zabbix_java_gateway.conf') do
  it { should be_file }
  its('content') { should include 'generated by Chef' }
end
